app:
  name: "S.Y.N.C."
  version: "0.1.0-alpha"
  codename: "Resonance"

logging:
  level: "INFO"
  file: log/assistant.log

speech:
  sample_rate: 16000
  chunk_size: 1024
  buffer_seconds: 5
  silence_threshold: 1.5
  stt_model: 
    "tiny": "Systran/faster-whisper-tiny"
    "tiny-en": "Systran/faster-whisper-tiny.en"
    "base": "Systran/faster-whisper-base"
    "base-en": "Systran/faster-whisper-base.en"
    "small": "Systran/faster-whisper-small"
    "small-en": "Systran/faster-whisper-small.en"
    "distil-large-v3.5": "distil-whisper/distil-large-v3.5"
    "large-v3-turbo": "mobiuslabsgmbh/faster-whisper-large-v3-turbo"
  piper_path: "bin/piper/piper.exe"
  piper_model_path: "models/tts/en_US-amy-medium.onnx"